# Generated by Django 6.0.4 on 2026-04-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='duration',
            field=models.PositiveIntegerField(help_text='Số ngày'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='slots',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
