# Generated by Django 6.0.4 on 2026-04-29 16:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_alter_tour_duration_alter_tour_slots'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='tour',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'tour')},
        ),
    ]
